name: ci-fresh

on:
  schedule:
    - cron: "0 8 1 * *"  # first of the month at 8 am UTC (3 am EST)

jobs:
  build-and-push-base:
    name: Base build and push
    uses: ./.github/workflows/docker-build-and-push.yml
    secrets: inherit
    with:
      file: ./base.Dockerfile
      tags: lyuhau/ark-ded:base

  build-and-push-fresh:
    name: Fresh build and push
    needs: build-and-push-base
    uses: ./.github/workflows/docker-build-and-push.yml
    with:
      context: .
      file: ./fresh.Dockerfile
      tags: lyuhau/ark-ded:incremental,lyuhau/ark-ded:latest
    secrets:
      DOCKERHUB_USERNAME: ${{ secrets.DOCKERHUB_USERNAME }}
      DOCKERHUB_ACCESS_TOKEN: ${{ secrets.DOCKERHUB_ACCESS_TOKEN }}
