name: ci-incremental

on:
  schedule:
    - cron: "*/5 * * * *"  # every 5 minutes

jobs:
  get-timeupdated:
    name: Get TIMEUPDATED
    uses: ./.github/workflows/steamcmd-appinfo.yml
    with:
      appid: 376030
      jsonpath: .data."376030".depots.branches.arklive.buildid

  build-and-push-incremental:
    name: Incremental build and push
    needs: get-timeupdated
    if: needs.get-timeupdated.outputs.value > vars.INCREMENTAL_LAST_BUILD_TIMEUPDATED
    uses: ./.github/workflows/docker-build-and-push.yml
    with:
      file: ./incremental.Dockerfile
      tags: lyuhau/ark-ded:incremental,lyuhau/ark-ded:latest
    secrets:
      DOCKERHUB_USERNAME: ${{ secrets.DOCKERHUB_USERNAME }}
      DOCKERHUB_ACCESS_TOKEN: ${{ secrets.DOCKERHUB_ACCESS_TOKEN }}

  update-last_build_timeupdated:
    name: Update LAST_BUILD_TIMEUPDATED
    needs: [get-timeupdated, build-and-push-incremental]
    uses: ./.github/workflows/update-repository-variable.yml
    with:
      name: INCREMENTAL_LAST_BUILD_TIMEUPDATED
      value: ${{ needs.get-timeupdated.outputs.value }}
    secrets:
      GITHUB_ACCESS_TOKEN: ${{ secrets.WRITEBACK_TOKEN }}
