name: update-repository-variable

on:
  workflow_call:
    inputs:
      name:
        required: true
        type: string
      value:
        required: true
        type: string
    secrets:
      GITHUB_ACCESS_TOKEN:
        required: true

jobs:
  update-repository-variable:
    name: Update repository variable
    runs-on: ubuntu-latest
    steps:
      -
        name: Update repository variable
        run: |
          curl -L \
            -X PATCH \
            -H "Accept: application/vnd.github+json" \
            -H "Authorization: Bearer ${{ secrets.GITHUB_ACCESS_TOKEN }}" \
            -H "X-GitHub-Api-Version: 2022-11-28" \
            https://api.github.com/repos/${{ github.repository }}/actions/variables/${{ inputs.name }} \
            -d '{"name":"${{ inputs.name }}","value":"${{ inputs.value }}"}'
